// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muxrifhrxglvamegpyhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11eHJpZmhyeGdsdmFtZWdweWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NjUwMjcsImV4cCI6MjA1MDQ0MTAyN30.DZdLXqpblGGP094d6qAY8z0StUBiw8OM0ubztN7lcLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);